In [1]:
import pandas as pd

In [3]:
data = [10, 20, 30, 40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [9]:
data = [1,2,3,4]
i = ['A','B','C','D']
series = pd.Series(data, index=i)
print(series)

A    1
B    2
C    3
D    4
dtype: int64


In [11]:
data = {'a': 10, 'b': 35, 'c':65}
series = pd.Series(data)
print(series)

a    10
b    35
c    65
dtype: int64


In [23]:
series.replace(35,40)

a    10
b    40
c    65
dtype: int64

In [31]:
data = {'Name':['Alice','Bob','Mary','Jod'],'Age':[25,30,34,27],'Country':["USA","UK","AUS","IND"]}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    Bob   30      UK
2   Mary   34     AUS
3    Jod   27     IND


In [33]:
#DataFrame: same datatype within the same column

In [39]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array, columns = ['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [41]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array)
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
